import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import NavSidebar from '@/components/sidebar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='min-h-screen w-full flex flex-col'>
          <Header />

          <div className='flex flex-1 overflow-hidden'>
            <div className='flex-shrink-0'>
              <NavSidebar />
            </div>
            <main className='flex-1 p-6 overflow-auto'>{children}</main>
          </div>
        </div>
      </body>
    </html>
  )
}
